version: 0.2
env:
  variables:
    #
    # NOTE: You need to replace these values!
    #
    ACCOUNT_NUMBER: "856777607988"
    ECR_REGION: "ap-southeast-1"
    ECR_REPOSITORY_NAME: "devops-workshop-app"
phases:
  pre_build:
    commands:
      # - echo Logging in to Amazon ECR...
      # - aws --version
      # - AWS_DEFAULT_REGION = ap-southeast-1
      # - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      # - REPOSITORY_URI=687152471527.dkr.ecr.{$AWS_DEFAULT_REGION}.amazonaws.com/devops-workshop-app
      # - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      # - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
      - echo Logging in to Amazon ECR...
      - echo "region ${AWS_DEFAULT_REGION}"
      - echo ACCOUNT_ID $ACCOUNT_ID
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_NAME=$REPOSITORY_NAME
      - REPOSITORY_URI=$ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$REPOSITORY_NAME
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date` for training.
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker image tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
artifacts:
  files: 
      - 'image*.json'
      - 'appspec.yaml'
      - 'taskdef.json'
  secondary-artifacts:
      DefinitionArtifact:
          files:
              - appspec.yaml
              - taskdef.json
      ImageArtifact:
          files:
              - imageDetail.json
